stages:
  - image
  - deps
  - build
  - test
  - release

variables:
  MIX_ENV: test
  MIX_HOME: $CI_PROJECT_DIR/.mix
  LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest

workflow:
  name: "Pipeline for branch: $CI_COMMIT_BRANCH"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

build image:
  stage: image
  # tags: [podman]
  image: quay.io/podman/stable
  variables:
    ELIXIR_VERSION: 1.14.2
    OTP_VERSION: 25.0.4
    ALPINE_VERSION: 3.16.1
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$ELIXIR_VERSION-$OTP_VERSION-$ALPINE_VERSION
  script:
    - echo $CI_REGISTRY_PASSWORD | podman login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - podman build --file build.Dockerfile --tag $IMAGE_TAG --tag $LATEST_IMAGE --build-arg ELIXIR_VERSION=$ELIXIR_VERSION --build-arg OTP_VERSION=$OTP_VERSION --build-arg ALPINE_VERSION=$ALPINE_VERSION .
    - podman push $IMAGE_TAG
    - podman push $LATEST_IMAGE
  rules:
    - changes:
        - .gitlab-ci.yml
        - build.Dockerfile

deps:elixir:
  stage: deps
  image: $LATEST_IMAGE
  # tags: [podman]
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
  script:
    - mix deps.get --only $MIX_ENV
    - mix loadpaths
  artifacts:
    paths:
      - .mix
      - _build
      - deps
      - mix.lock
  cache:
    paths:
      - .mix
      - _build
      - deps
    key:
      files:
        - mix.lock

lint:elixir:
  stage: test
  # tags: [podman]
  image: $LATEST_IMAGE
  dependencies: [deps:elixir]
  script:
    - make lint

test:elixir:
  stage: test
  # tags: [podman]
  image: $LATEST_IMAGE
  services: [postgres:14-alpine]
  dependencies: [deps:elixir]
  variables:
    FF_NETWORK_PER_BUILD: 1
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  script:
    - make test

release:
  stage: release
  image: alpine:latest
  # tags: [podman]
  before_script:
    - apk add --no-cache curl
    - curl -L https://fly.io/install.sh | sh
  script:
    - /root/.fly/bin/flyctl deploy --detach
  when: manual
  only:
    - main
