const MIME_TYPES: &[(&str, &str)] = &[
    ("css", "text/css"),
    ("eot", "application/vnd.ms-opentype"),
    ("gif", "image/gif"),
    ("html", "application/xhtml+xml"),
    ("jpeg", "image/jpeg"),
    ("jpg", "image/jpeg"),
    ("js", "text/javascript"),
    ("mp3", "audio/mpeg"),
    ("mp4", "video/mp4"),
    ("ncx", "application/x-dtbncx+xml"),
    ("opf", "application/oebps-package+xml"),
    ("otf", "application/vnd.ms-opentype"),
    ("png", "image/png"),
    ("svg", "image/svg+xml"),
    ("ttc", "application/vnd.ms-opentype"),
    ("ttf", "application/vnd.ms-opentype"),
    ("txt", "text/plain"),
    ("woff", "application/font-woff"),
    ("xhtml", "application/xhtml+xml"),
];
