name: Build and push image

on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - "**/build-push.yml"
  schedule:
    - cron: "54 07 12 * *" # on 12th day of every month at 07:54

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Build and push latest builder image with Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.14.2
            otp: 25.0.4
            alpine-version: 3.16.1
            aliases: |
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:1.14.2-25.0.4
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:1.14-25.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-dev-${{ matrix.alpine-version }}-${{ matrix.otp }}-${{ matrix.elixir }}
          restore-keys: |
            ${{ runner.os }}-buildx-dev-${{ matrix.alpine-version }}-${{ matrix.otp }}-${{ matrix.elixir }}
            ${{ runner.os }}-buildx-dev-${{ matrix.alpine-version }}-${{ matrix.otp }}
            ${{ runner.os }}-buildx-dev-${{ matrix.alpine-version }}
            ${{ runner.os }}-buildx-dev

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: build.Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.alpine-version }}
            ${{ matrix.aliases }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            ELIXIR_VERSION=${{ matrix.elixir }}
            OTP_VERSION=${{ matrix.otp }}
            ALPINE_VERSION=${{ matrix.alpine-version }}
