name: Elixir CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main", "develop"]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    services:
      postgres:
        image: postgres:14-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    name: Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [25.x]
        elixir: [1.14.x]
        include:
          - coverage: false
            lint: true

    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache deps
        uses: actions/cache@v3
        id: cache-deps
        env:
          cache-name: cache-elixir-deps
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-

      - name: Cache compiled build
        id: cache-build
        uses: actions/cache@v3
        env:
          cache-name: cache-compiled-build
        with:
          path: _build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Check no unused dependencies
        run: mix deps.unlock --check-unused
        if: ${{matrix.lint}}

      - name: Check retired dependencies
        run: mix hex.audit
        if: ${{matrix.lint}}

      - name: Compiles without warnings
        run: mix compile --warnings-as-errors
        if: ${{matrix.lint}}

      - name: Check Formatting
        run: mix format --check-formatted
        if: ${{matrix.lint}}

      - name: Check Credo Warnings
        run: mix credo --strict --only warning

      - name: Check for compile-time dependencies
        run: mix xref graph --label compile-connected --fail-above 0

      - name: Run tests
        run: mix test
        if: ${{!matrix.coverage}}

      - name: Run tests with coverage
        run: mix coveralls
        if: ${{matrix.coverage}}
